#ifndef UNITYSYSTEMTRAY_GLOBAL_H
#define UNITYSYSTEMTRAY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UNITYSYSTEMTRAY_LIBRARY)
#  define UNITYSYSTEMTRAYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UNITYSYSTEMTRAYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UNITYSYSTEMTRAY_GLOBAL_H
